version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/home/app
    depends_on:
      - postgresql


  postgresql:
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: admin_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4:6"
    environment:
      PGADMIN_DEFAULT_EMAIL: "mateo.valenzuela.dev@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "80:80"
    depends_on:
      - postgresql

volumes:
  postgres-data:
